---
title: "Exploratory Data Analysis"
author: "Devi Annanda"
date: "15 August 2021, Updated `r format(Sys.Date(), '%d %B %Y')`"
output: 
  html_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load library
library(tidyverse)
library(lubridate)

library(maps)
library(mapdata)
```

```{r data}
# load data
load(file = here("data/data.RData"))
```

## Data Cleaning

```{r data-cleaning}
# combine dataset
data_combined <- 
  engagement %>% 
  
### JOINING
  
  # match reference variable for left_join
  mutate_at(.vars = c("lp_id", "pct_access", "engagement_index", "district_id"),
            as.numeric) %>% 
  
  mutate(district_id = as.double(district_id),
         lp_id = as.double(lp_id)) %>% 
  # left join
  left_join(districts, by = "district_id") %>% 
  left_join(products, by = c("lp_id" = "LP ID")) %>% 
  
### CLEANING
  mutate(
    
    # missing values
    state = na_if(state, "NaN"),
    
    # date
    time = ymd(time)
  )
```


## Data Exploration

### Missing Variables

```{r missing-var}
# check missing product name
missing_product_name <- 
  engagement %>% 
  
  # left-join
  mutate_at(lp_id = as.numeric(lp_id)) %>% 
  left_join(products, by = c("lp_id" = "LP ID")) %>% 
  
  # filter for id and product name
  select(lp_id, `Product Name`) %>% 
  
  # filter for NA in product name
  dplyr::filter(is.na(`Product Name`)) %>% 
  
  # count unique id and arrange in desc order
  count(lp_id) %>% 
  arrange(desc(n))


# product id with missing product name
nrow(missing_product_name)

# total engagemnet observations with missing product name
sum(missing_product_name$n)
```


### Primary Essential Function

```{r primary-essential-function}
# primary-essential-function OVERALL RANKING
data_combined %>% 
  count(`Primary Essential Function`) %>% 
  ungroup() %>% 
  arrange(desc(n))
```

Definition of

- LC
- SDO
- CM

### Provider/Company Name
```{r provider}
# Provider/Company Name OVERALL RANKING
data_combined %>% 
  count(`Provider/Company Name`) %>% 
  ungroup() %>% 
  arrange(desc(n))
```

### Product Name
```{r product-name}
# Product name OVERALL RANKING
data_combined %>% 
  count(`Product Name`) %>% 
  ungroup() %>% 
  arrange(desc(n))
```

### State
```{r state}
# state count OVERALL RANKING
state_data <- 
  data_combined %>% 
  count(state) %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  mutate(state = tolower(state))
```


## Data Visualization

```{r monthly-count-plot}
# count of engagement observation by month
ts <-
  data_combined %>% 
  mutate(month = month(time, label = TRUE)) %>% 
  count(month) %>% 
  ungroup()

# bar plot of count by month
ggplot(data = ts,
       aes(x = month,
           y = n)) +
  geom_bar(stat = "identity")
```


```{r count-state-plot}
# count of engagement obs by state map plot

# prepare data
state <- map_data("state") %>% 
  left_join(state_data, by = c("region" = "state"))

# plot
plot <- 
  ggplot(data=state, 
         aes(x=long, 
             y=lat, 
             fill=n, 
             group=group, 
             label = region)) + # for plotly label
  # state outline
  geom_polygon(color = "white") + 
  # formatting
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        legend.position = "right") + 
  # label
  labs(
    title = "Count of engagemnet observations by state",
    fill = "Count"
  ) +
  coord_fixed(1.3)

# interactive plot
plotly::ggplotly(plot)
```

```{r engagement-state-plot}
# average engagement by state plot
engagement_by_state <- 
  # prepare data
  data_combined %>% 
  group_by(state) %>%
  summarise(avg_engagement = mean(engagement_index, na.rm = TRUE)) %>% 
  ungroup() %>% 
  # to match join ref
  mutate(state = tolower(state))

# join data
engagement_by_state_map <- 
  map_data("state") %>% 
  left_join(engagement_by_state, by = c("region" = "state"))

# plot
ggplot(data = engagement_by_state_map, 
       aes(x=long, 
           y=lat, 
           fill=avg_engagement, 
           group=group, 
           label = region)) + 
  # state outline
  geom_polygon(color = "white") + 
  # formatting
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        legend.position = "right") + 
  # labels
  labs(
    title = "Average engagement by state",
    fill = "engagement"
  ) +
  coord_fixed(1.3)
```

```{r scatterplot}
# join dataset
state_data %>% 
  left_join(engagement_by_state, by = "state") %>% 
  # remove missing values
  dplyr::filter(! is.na(state)) %>% 
  
  # plot
  ggplot(aes(
    x = n,
    y = avg_engagement
  )) +
  geom_point() +
  # add text label
  geom_text(aes(label = state), hjust = -0.1) +
  # expand limits
  scale_x_continuous(limits = c(0, 3000000)) +
  # labs
  labs(
    y = "Average Engagement",
    x = "Engagement Count",
    title = "Relationship between Count and Average Engagement"
  )

```

