---
title: "Initial EDA"
author: "Devi Annanda"
date: "04 August 2021, Updated (`r format(Sys.Date(), '%d %B %Y')`)"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE
                      )


```

## Load Libraries

```{r libraries}
# load libraries

# data wrangling
library(tidyverse)
library(here)
library(glue)
```

## Load the data

Load raw dataset and save into an RData format. 

```{r load-engagement-data}
# load engagement data

# read csv with filename as column
filename <- function(x) read_csv(x, col_types = cols(.default = "c")) %>% 
  mutate(district_id = gsub(".csv", "", basename(x)))

# load engagement as one dataframe
engagement <-
    list.files(path = here("data/engagement_data"), 
               pattern = "*.csv",
               full.names = TRUE) %>% 
  map_df(filename) %>% 
  as_tibble()

## reference:
## https://stackoverflow.com/questions/44462494/include-csv-filename-when-reading-data-into-r-using-list-files

# load product and districts data
products <- read_csv(here("data", "products_info.csv"))
districts <- read_csv(here("data", "districts_info.csv"))

# compile dataset and save it into an RData format
save(engagement, products, districts, file = here("data/data.RData"))
```

## Reading the data

In other rmarkdown file for this project, the raw data will be loaded by:

```{r}
load(file = here("data/data.RData"))
```


